### ISSUE TITLE
Change navigation bar

### ISSUE THREAD

**Issue by mishmosh** [application-research/ipfs-events#102]
Navigation bar:
- Should highlight event-specific sections (About, Tracks, Tickets, Schedule, Speakers, FAQ) with 2 sections currently hidden (Schedule, Speakers). The footer still contains links to other events.
- Should be pinned to the top when scrolling.

See 2022.ipfs.camp for example.

<img width="1300" alt="image" src="https://github.com/application-research/ipfs-events/assets/1306020/369e8828-b088-4233-8289-9b8754650f8b">

**Comment by APiligrim** [comment]
@mishmosh the navbar and footer have been updated! 😃

**Comment by xBalbinus** [comment]
Thanks @APiligrim !
