### ISSUE TITLE
Sponsors section

### ISSUE THREAD

**Issue by mishmosh** [application-research/ipfs-events#103]
This website needs a Sponsors section, probably after the FAQs section. Please set it up to have 2-3 tiers of logo sizes. The largest tier should have 2 logos currently:
1. IPFS (![Ipfs-logo-1024-ice-text](https://github.com/application-research/ipfs-events/assets/1306020/602b4f2f-552d-4aaa-a7e5-30341a9a58e8)
)
2. Protocol Labs

Should all logos be white on black background?

**Comment by xBalbinus** [comment]
Implemented

**Comment by xBalbinus** [comment]
Ah thanks.
